apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: custompods.heheh.example.com
spec:
  group: heheh.example.com 
  names:
    plural: custompods
    singular: custompod
    kind: Custompod
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                container:
                  type: object
                  properties: 
                    image:
                      type: string
                    name:
                      type: string
                    imagePullPolicy:
                      type: string
                    # required:
                    # - name
                    # - imagePullPolicy
                    # - image
                    # type: object