apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: destroyments.heheh.com
spec:
    group: heheh.com
    names:
      plural: destroyments
      singular: destroyment
      kind: Destroyment
      shortNames:
        - ds
    scope: Namespaced
    versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                    replicas:
                      type: integer
                    container:
                      type: object
                      properties:
                        image:
                          type: string
                        port:
                          type: integer




    
